import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container } from "@mui/material";
import AuthContext from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <AuthContext>
          <Container maxWidth="md" sx={{ my: 6 }}>
            {children}
          </Container>
        </AuthContext>
      </body>
    </html>
  );
}
